apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: 767398103155.dkr.ecr.ap-southeast-1.amazonaws.com/edstock-ui:b75674d
                  env:
                      - name: NEXT_PUBLIC_API_BASE_URL
                        value: "http://a42a60e226a4e4d2ea544ca43643b7fb-1750942512.ap-southeast-1.elb.amazonaws.com/"
                  ports:
                      - containerPort: 80
